
baseURL = "https://enchanting-crepe-694c13.netlify.app/"
# disableKinds = [ "section", "taxonomy", "term", "tags"]

# [outputs]
# home = ["HTML"]

[module]
[module.hugoVersion]
# We use hugo.Deps to list dependencies, which was added in Hugo 0.92.0
min = "0.92.0"

[[module.imports]]
path="github.com/gohugoio/hugo-mod-bootstrap-scss/v4"